service: task-manager
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /
          method: get
  getTask:
    handler: get-task.handler
    events:
      - httpApi:
          path: /task
          method: get
  putTask:
    handler: put-task.handler
    events:
      - httpApi:
          path: /
          method: put
