org: brandtbasaran
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  provider:
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-task-manager-${sls:stage}
  name: aws
  runtime: nodejs14.x
  environment: 
    DYNAMODB_TASK_MANAGER: ${self:service}-task-manager-${sls:stage}

functions:
  provider:
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-task-manager-${sls:stage}
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    task-manager:
      Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            -AttrubuteName: primary_key
              AttributeType: S
            BillingMode: PAY_PER_REQUEST
            KeySchema:
              -AttributeName: primary_key
                KeyType: HASH
              TableName: ${self:service}-task-manager-${sls:stage}
