service: task-manager
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_TASK_TABLE: ${self:service}-taskTable-${sls:stage}
iamRoleStatements:
      - Effect: "Allow"
        Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
        Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-taskTable-${sls:stage}
functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /
          method: get
  getTask:
    handler: get-task.handler
    events:
      - httpApi:
          path: /task
          method: get
  putTask:
    handler: put-task.handler
    events:
      - httpApi:
          path: /
          method: put
  postTask:
    handler: post-task.handler
    events:
      - httpApi:
          path: /
          method: post
  deleteTask:
    handler: delete-task.handler
    events:
      - httpApi:
          path: /
          method: delete
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-taskTable-${sls:stage}
