// this file was generated by serverless-auto-swagger
module.exports = {
  swagger: "2.0",
  info: {
    title: "task-manager",
    version: "1",
  },
  paths: {
    "/task": {
      get: {
        summary: "getTask",
        description: "",
        operationId: "getTask.get./task",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "200 response",
          },
        },
      },
      post: {
        summary: "postTask",
        description: "",
        operationId: "postTask.post./task",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "200 response",
          },
        },
      },
    },
    "/": {
      put: {
        summary: "putTask",
        description: "",
        operationId: "putTask.put./task",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "200 response",
          },
        },
      },
      delete: {
        summary: "deleteTask",
        description: "",
        operationId: "deleteTask.delete./task",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "200 response",
          },
        },
      },
    },
  },
  definitions: {},
  securityDefinitions: {},
};
