// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "task-manager",
    "version": "1"
  },
  "paths": {},
  "definitions": {},
  "securityDefinitions": {}
};